version: '3.4'


services:
    app:
        image: python:3
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_HOST=db
            - DB_PORT=6379
        ports:
            - "9443:9443"
        depends_on:
            - db

    db:
        image: redis
        ports:
            - "6379:6379"
